from deepattern.objects.transitional_object import TransitionalObject
from deepattern.objects.config_singleton import ConfigSingleton
from deepattern.objects.logger_singleton import LoggerSingleton
from deepattern.objects.model import Model