from patterns.chain_of_responsibility.abstract_handler import AbstractHandler
from patterns.chain_of_responsibility.handler import Handler
from patterns.strategy.strategy import Strategy
from patterns.strategy.context import Context