from deepattern.patterns.chain_of_responsibility.handler import Handler
from deepattern.patterns.strategy.strategy import Strategy
from deepattern.patterns.strategy.context import Context
from deepattern.patterns.chain_of_responsibility.generic_handler import GenericHandler
from deepattern.patterns.chain_of_responsibility.strategy_handler import StrategyHandler
from deepattern.patterns.singleton.singleton_meta import SingletonMeta